routes/web.php
<?php

use App\Http\Controllers\Admin\ACL\RoleController;
use App\Http\Controllers\Admin\CategoryVideoController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ResumeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Site\CompanyController;
use App\Http\Controllers\Site\PartnershipController;
use App\Http\Controllers\Site\ResumeController as SiteResumeController;
use App\Http\Controllers\Site\VideoController as SiteVideoController;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Site
Route::name('site.')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('index');

//    Route::get('/carreiras', function() {
//        return view('site.carreiras');
//    });
//
    Route::get('/videos', SiteVideoController::class)->name('video');
    Route::get('empresa', CompanyController::class)->name('company');
    Route::get('motivos', PartnershipController::class)->name('partnership');

    Route::get(
        'produtos/mudas',
        fn (): View => view('site.plant_seedlings', ['pageName' => 'Mudas'])
    )->name('seedlings');

    Route::get(
        'produtos/porta-enxertos',
        fn (): View => view('site.grafts', ['pageName' => 'Porta-enxertos'])
    )->name('grafts');

    Route::get(
        'produtos/borbulhas',
        fn (): View => view('site.bubbles', ['pageName' => 'Borbulhas'])
    )->name('bubbles');

    Route::get(
        'contato',
        fn (): View => view('site.contact', ['pageName' => 'Contato'])
    )->name('contact');

    Route::get('carreiras', [SiteResumeController::class, 'index'])->name('career');
    Route::post('carreiras', [SiteResumeController::class, 'store'])->name('career-send');
});


Route::prefix('admin')->name('admin.')->group(function () {
    Route::group(
        ['middleware' => ['auth']],
        function () {
            // Dashboard
            Route::get('/', DashboardController::class)->name('dashboard.index');

            // Perfil
            Route::prefix('perfil')->name('profile.')->group(function () {
                Route::get('/', [ProfileController::class, 'index'])->name('index');
                Route::put('update', [ProfileController::class, 'update'])->name('update');
            });

            // Usuários
            Route::prefix('usuarios')->name('user.')->group(function () {
                Route::get('/', [UserController::class, 'index'])
                    ->name('index')
                    ->can('visualizar usuários');

                Route::group(['middleware' => ['can:cadastrar usuário']], function () {
                    Route::get('/cadastrar', [UserController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [UserController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar usuário']], function () {
                    Route::get('editar/{id}', [UserController::class, 'edit'])->name('edit');
                    Route::put('editar/{id}', [UserController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{id}', [UserController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir usuário');
            });

            // Cargos
            Route::prefix('cargos')->name('role.')->group(function () {

                Route::get('/', [RoleController::class, 'index'])
                    ->name('index')
                    ->can('visualizar cargos');

                Route::group(['middleware' => ['can:cadastrar cargo']], function () {
                    Route::get('/cadastrar', [RoleController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [RoleController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar cargo']], function () {
                    Route::get('editar/{id}', [RoleController::class, 'edit'])->name('edit');
                    Route::put('editar/{id}', [RoleController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{id}', [RoleController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir cargo');

            });

            // Departamentos
            Route::prefix('departamentos')->name('department.')->group(function () {
                Route::get('/', [DepartmentController::class, 'index'])
                    ->name('index')
                    ->can('visualizar departamentos');

                Route::group(['middleware' => ['can:cadastrar departamento']], function () {
                    Route::get('/cadastrar', [DepartmentController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [DepartmentController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar departamento']], function () {
                    Route::get('editar/{department}', [DepartmentController::class, 'edit'])->name('edit');
                    Route::put('editar/{department}', [DepartmentController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{department}', [DepartmentController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir departamento');
            });

            // Currículos
            Route::prefix('curriculos')->name('resume.')->group(function () {
                Route::get('/', [ResumeController::class, 'index'])
                    ->name('index')
                    ->can('visualizar curriculos');

                Route::get('/download/{resume}', [ResumeController::class, 'downloadResume'])
                    ->name('download')
                    ->can('baixar curriculo');

                Route::delete('excluir/{curriculo}', [DepartmentController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir curriculo');
            });

            // Categorias de vídeos
            Route::prefix('categorias-videos')->name('category_video.')->group(function () {
                Route::get('/', [CategoryVideoController::class, 'index'])
                    ->name('index')
                    ->can('visualizar categorias de video');

                Route::group(['middleware' => ['can:cadastrar categoria de video']], function () {
                    Route::get('/cadastrar', [CategoryVideoController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [CategoryVideoController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar categoria de video']], function () {
                    Route::get('editar/{categoryVideo}', [CategoryVideoController::class, 'edit'])->name('edit');
                    Route::put('editar/{categoryVideo}', [CategoryVideoController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{categoryVideo}', [CategoryVideoController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir categoria de video');
            });

            // Vídeos
            Route::prefix('videos')->name('video.')->group(function () {
                Route::get('/', [VideoController::class, 'index'])
                    ->name('index')
                    ->can('visualizar videos');

                Route::group(['middleware' => ['can:cadastrar video']], function () {
                    Route::get('/cadastrar', [VideoController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [VideoController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar video']], function () {
                    Route::get('editar/{video}', [VideoController::class, 'edit'])->name('edit');
                    Route::put('editar/{video}', [VideoController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{video}', [VideoController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir video');
            });

        }
    );
});


Auth::routes();

app/Models/CategoryVideo.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

class CategoryVideo extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
        'color'
    ];

    public function videos(): HasMany
    {
        return $this->hasMany(Video::class);
    }
}

app/Http/Controllers/Admin/CategoryVideoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryVideoRequest;
use App\Models\CategoryVideo;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;

class CategoryVideoController extends Controller
{
    private CategoryVideo $categoryVideo;

    public function __construct(CategoryVideo $categoryVideo)
    {
        $this->categoryVideo = $categoryVideo;
    }

    public function index(): View
    {
        return view('admin.category_video.index', [
            'categories' => $this->categoryVideo->orderBy('id', 'DESC')->get()
        ]);
    }

    public function create(): View
    {
        return view('admin.category_video.form');
    }

    public function store(CategoryVideoRequest $request): RedirectResponse
    {
        $data = $request->all();

        try {
            $this->categoryVideo->create($data);

            Alert('Sucesso!', 'Adicionado com sucesso!', 'success');
            return redirect()->route('admin.category_video.index');
        } catch (\Throwable $th) {

            if (env('APP_DEBUG')) {
                dd($th->getMessage());
            }

            Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');
            return redirect()
                ->back()
                ->withErro('Ocorreu um erro!')
                ->withInput();
        }
    }

    public function edit(CategoryVideo $categoryVideo): View
    {
        return view('admin.category_video.form', [
            'category' => $categoryVideo->select('id', 'name', 'color')->first()
        ]);
    }

    public function update(CategoryVideoRequest $request, CategoryVideo $categoryVideo): RedirectResponse
    {
        $data = $request->all();

        try {
            $categoryVideo->update($data);

            Alert('Sucesso!', 'Atualizado com sucesso!', 'success');
            return redirect()->route('admin.category_video.index');
        } catch (\Throwable $th) {
            Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');
            return redirect()
                ->back()
                ->withErro('Ocorreu um erro!')
                ->withInput();
        }
    }

    public function destroy(CategoryVideo $categoryVideo): RedirectResponse
    {
        try {
            $categoryVideo->delete();

            Alert('Sucesso!', 'Excluído com sucesso!', 'success');
            return redirect()->back();
        } catch (\Throwable $th) {
            Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');
            return redirect()
                ->back()
                ->withErro('Ocorreu um erro!')
                ->withInput();
        }
    }
}

resources/views/admin/category_video/form.blade.php
@extends('adminlte::page')

@section('title', isset($category) ? 'Edição de categoria de vídeo' : 'Cadastrar categoria de vídeo')

@section('content_header')
    <div class="row">
        <div class="col-sm-6">
            <h1>
                Categoria de vídeo
            </h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard.index') }}">
                        Início
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.category_video.index') }}">
                        categorias de vídeo
                    </a>
                </li>

                <li class="breadcrumb-item active">
                    Adicionar
                </li>
            </ol>
        </div>
    </div>
@endsection

@section('content')
    @include('sweetalert::alert')

    <div class="card card-outline card-success">
        <div class="card-header">
            <div class="card-title">
                {{ isset($category) ? 'Edição de categoria de vídeo' : 'Cadastrar categoria de vídeo' }}
            </div>
        </div>

        <div class="card-body">
            @if (isset($category))
                <form action="{{ route('admin.category_video.update', $category->id) }}" method="POST">
                @method('PUT')
            @else
                <form action="{{ route('admin.category_video.store') }}" method="POST">
                    @endif

                    @csrf

                    <div class="form-group">
                        <div class="form-row">
                            <div class="col-md-10">
                                <label for="name">Nome <span class="text-danger">*</span></label>
                                <input type="text" name="name" id="name" class="form-control @error('name') is-invalid @enderror" value="{{ $category->name ?? old('name') }}" maxlength="150" required>

                                @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>

                            <div class="col-md-2">
                                <label for="name">Cor da fonte<span class="text-danger">*</span></label>
                                <input type="color" name="color" id="color" class="form-control @error('color') is-invalid @enderror" value="{{ $category->color ?? old('color') }}" required>

                                @error('color')
                                    <span class="invalid-feedback" role="alert">
                                        {{ $message }}
                                    </span>
                                @enderror
                            </div>
                        </div>


                    </div>


                    <div class="form-group">
                        <small>(<span class="text-danger">*</span>) Campos obrigatórios</small>
                    </div>


                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-save"></i>
                        {{ isset($category) ? 'Atualizar' : 'Cadastrar' }}
                    </button>

                    <a href="{{ route('admin.category_video.index') }}" class="btn btn-secondary">
                        <i class="fa fa-times"></i>
                        Cancelar
                    </a>
                </form>
        </div>
    </div>
@endsection

resources/views/admin/category_video/index.blade.php
@extends('adminlte::page')

@section('title', 'Categorias de vídeo')

@section('content_header')
    <div class="row">
        <div class="col-sm-6">
            <h1>
                Categorias de vídeo
            </h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard.index') }}">
                        Início
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    Categorias de vídeo
                </li>
            </ol>
        </div>
    </div>
@endsection

@section('content')
    @include('sweetalert::alert')

    <div class="card card-outline card-primary">
        <div class="card-header">
            <div class="card-title">
                Lista de categorias de vídeo
            </div>
        </div>

        <div class="row justify-content-end mr-3 mt-3">
            <a href="{{ route('admin.category_video.create') }}" class="btn btn-success">
                <i class="fa fa-plus"></i>
                Adicionar
            </a>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped text-center">
                    <thead>
                    <tr>
                        <th>Nome</th>
                        <th>Cor da fonte</th>
                        <th>Ações</th>
                    </tr>
                    </thead>

                    <tbody>
                    @foreach ($categories as $category)
                        <tr>
                            <td>
                                {{ $category->name }}
                            </td>

                            <td>
                                <i class="fa fa-square fa-2x" style="color: {{ $category->color }}"></i>
                            </td>

                            <td>
                                @can('editar categoria de video')
                                    <a href="{{ route('admin.category_video.edit', $category->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Editar">
                                        <i class="fa fa-edit"></i>
                                    </a>
                                @endcan

                                @can('excluir categoria de video')
                                    <form action="{{ route('admin.category_video.destroy', $category->id) }}" class="d-inline" method="POST">
                                        @csrf
                                        @method('DELETE')
                                        <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Tem certeza que deseja excluir?')" data-toggle="tooltip" data-placement="top" title="Excluir">
                                            <i class="fa fa-trash-alt"></i>
                                        </button>
                                    </form>
                                @endcan
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection