routes/web.php
<?php

use App\Http\Controllers\Admin\ACL\RoleController;
use App\Http\Controllers\Admin\CategoryVideoController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ResumeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Site\CompanyController;
use App\Http\Controllers\Site\PartnershipController;
use App\Http\Controllers\Site\ResumeController as SiteResumeController;
use App\Http\Controllers\Site\VideoController as SiteVideoController;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Site
Route::name('site.')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('index');

//    Route::get('/carreiras', function() {
//        return view('site.carreiras');
//    });
//
    Route::get('/videos', SiteVideoController::class)->name('video');
    Route::get('empresa', CompanyController::class)->name('company');
    Route::get('motivos', PartnershipController::class)->name('partnership');

    Route::get(
        'produtos/mudas',
        fn (): View => view('site.plant_seedlings', ['pageName' => 'Mudas'])
    )->name('seedlings');

    Route::get(
        'produtos/porta-enxertos',
        fn (): View => view('site.grafts', ['pageName' => 'Porta-enxertos'])
    )->name('grafts');

    Route::get(
        'produtos/borbulhas',
        fn (): View => view('site.bubbles', ['pageName' => 'Borbulhas'])
    )->name('bubbles');

    Route::get(
        'contato',
        fn (): View => view('site.contact', ['pageName' => 'Contato'])
    )->name('contact');

    Route::get('carreiras', [SiteResumeController::class, 'index'])->name('career');
    Route::post('carreiras', [SiteResumeController::class, 'store'])->name('career-send');
});


Route::prefix('admin')->name('admin.')->group(function () {
    Route::group(
        ['middleware' => ['auth']],
        function () {
            // Dashboard
            Route::get('/', DashboardController::class)->name('dashboard.index');

            // Perfil
            Route::prefix('perfil')->name('profile.')->group(function () {
                Route::get('/', [ProfileController::class, 'index'])->name('index');
                Route::put('update', [ProfileController::class, 'update'])->name('update');
            });

            // Usuários
            Route::prefix('usuarios')->name('user.')->group(function () {
                Route::get('/', [UserController::class, 'index'])
                    ->name('index')
                    ->can('visualizar usuários');

                Route::group(['middleware' => ['can:cadastrar usuário']], function () {
                    Route::get('/cadastrar', [UserController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [UserController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar usuário']], function () {
                    Route::get('editar/{id}', [UserController::class, 'edit'])->name('edit');
                    Route::put('editar/{id}', [UserController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{id}', [UserController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir usuário');
            });

            // Cargos
            Route::prefix('cargos')->name('role.')->group(function () {

                Route::get('/', [RoleController::class, 'index'])
                    ->name('index')
                    ->can('visualizar cargos');

                Route::group(['middleware' => ['can:cadastrar cargo']], function () {
                    Route::get('/cadastrar', [RoleController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [RoleController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar cargo']], function () {
                    Route::get('editar/{id}', [RoleController::class, 'edit'])->name('edit');
                    Route::put('editar/{id}', [RoleController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{id}', [RoleController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir cargo');

            });

            // Departamentos
            Route::prefix('departamentos')->name('department.')->group(function () {
                Route::get('/', [DepartmentController::class, 'index'])
                    ->name('index')
                    ->can('visualizar departamentos');

                Route::group(['middleware' => ['can:cadastrar departamento']], function () {
                    Route::get('/cadastrar', [DepartmentController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [DepartmentController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar departamento']], function () {
                    Route::get('editar/{department}', [DepartmentController::class, 'edit'])->name('edit');
                    Route::put('editar/{department}', [DepartmentController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{department}', [DepartmentController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir departamento');
            });

            // Currículos
            Route::prefix('curriculos')->name('resume.')->group(function () {
                Route::get('/', [ResumeController::class, 'index'])
                    ->name('index')
                    ->can('visualizar curriculos');

                Route::get('/download/{resume}', [ResumeController::class, 'downloadResume'])
                    ->name('download')
                    ->can('baixar curriculo');

                Route::delete('excluir/{curriculo}', [DepartmentController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir curriculo');
            });

            // Categorias de vídeos
            Route::prefix('categorias-videos')->name('category_video.')->group(function () {
                Route::get('/', [CategoryVideoController::class, 'index'])
                    ->name('index')
                    ->can('visualizar categorias de video');

                Route::group(['middleware' => ['can:cadastrar categoria de video']], function () {
                    Route::get('/cadastrar', [CategoryVideoController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [CategoryVideoController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar categoria de video']], function () {
                    Route::get('editar/{categoryVideo}', [CategoryVideoController::class, 'edit'])->name('edit');
                    Route::put('editar/{categoryVideo}', [CategoryVideoController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{categoryVideo}', [CategoryVideoController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir categoria de video');
            });

            // Vídeos
            Route::prefix('videos')->name('video.')->group(function () {
                Route::get('/', [VideoController::class, 'index'])
                    ->name('index')
                    ->can('visualizar videos');

                Route::group(['middleware' => ['can:cadastrar video']], function () {
                    Route::get('/cadastrar', [VideoController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [VideoController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar video']], function () {
                    Route::get('editar/{video}', [VideoController::class, 'edit'])->name('edit');
                    Route::put('editar/{video}', [VideoController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{video}', [VideoController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir video');
            });

        }
    );
});


Auth::routes();

app/Models/Video.php
<?php

namespace App\Models;

use App\Enums\TypeVideoEnum;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class Video extends Model
{
    use HasFactory;

    protected $fillable = [
        'title',
        'type_video',
        'category_video_id',
        'video',
        'order',
        'image'
    ];

    protected $appends = [
        'class_player',
        'is_upload',
        'video_id',
        'image_link'
    ];

    public function category(): BelongsTo
    {
        return $this->belongsTo(CategoryVideo::class, 'category_video_id');
    }

    public function getClassPlayerAttribute(): string
    {
        if ($this->type_video === TypeVideoEnum::VIDEO_YOUTUBE || $this->type_video === TypeVideoEnum::VIDEO_UPLOAD) {
            return 'js-modal-btn';
        }

        if ($this->type_video === TypeVideoEnum::VIDEO_VIMEO) {
            return 'js-modal-btn-vimeo';
        }

        return '';
    }

    public function getIsUploadAttribute(): bool
    {
        return TypeVideoEnum::ARRAY_TYPE_VIDEOS[$this->type_video] === TypeVideoEnum::VIDEO_UPLOAD_STRING;
    }

    public function getVideoIdAttribute(): string
    {
        if ($this->type_video === TypeVideoEnum::VIDEO_YOUTUBE) {
            $url = explode('/', $this->video);

            return (string) end($url);
        }

        if ($this->type_video === TypeVideoEnum::VIDEO_VIMEO) {
            return (string) filter_var($this->video, FILTER_SANITIZE_NUMBER_INT);
        }

        return '';
    }

    public function getImageLinkAttribute(): string
    {
        return $this->image ? asset('storage/' . $this->image) : asset('/img/bg-title-header-produtos.jpg');
    }
}

app/Http/Controllers/Admin/VideoController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Enums\TypeVideoEnum;
use App\Http\Controllers\Controller;
use App\Http\Requests\VideoRequest;
use App\Models\CategoryVideo;
use App\Models\Video;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\UploadedFile;
use Illuminate\Support\Facades\Storage;

class VideoController extends Controller
{
    private Video $video;
    private CategoryVideo $categoryVideo;

    public function __construct(Video $video, CategoryVideo $categoryVideo)
    {
        $this->video = $video;
        $this->categoryVideo = $categoryVideo;
    }

    public function index(): View
    {
        return view('admin.video.index', [
            'videos' => $this->video->with('category')->orderBy('created_at', 'DESC')->get()
        ]);
    }

    public function create(): View
    {
        return view('admin.video.form', [
            'categories' => $this->categoryVideo->select('id', 'name')->orderBy('name', 'DESC')->get(),
            'types' => TypeVideoEnum::ARRAY_TYPE_VIDEOS
        ]);
    }

    public function store(VideoRequest $request): RedirectResponse
    {
        $data = $request->all();

        /** @var UploadedFile|null $videoUpload */
        $videoUpload = $data['video_upload'] ?? null;

        /** @var UploadedFile|null $image */
        $image = $data['image'] ?? null;

        try {
            if ($videoUpload !== null) {
                if (!$videoSaved = $videoUpload->store('videos')) {
                    Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');

                    return redirect()
                        ->back()
                        ->withInput();
                }

                $data['video'] = $videoSaved;
            }

            if ($image !== null) {
                if (!$imageSaved = $image->store('images')) {
                    Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');

                    return redirect()
                        ->back()
                        ->withInput();
                }

                $data['image'] = $imageSaved;
            }

            $this->video->create($data);

            Alert('Sucesso!', 'Adicionado com sucesso!', 'success');
            return redirect()->route('admin.video.index');
        } catch (\Throwable $th) {

            if (env('APP_DEBUG')) {
                dd($th->getMessage());
            }

            Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');
            return redirect()
                ->back()
                ->withErro('Ocorreu um erro!')
                ->withInput();
        }
    }

    public function edit(Video $video): View
    {
        return view('admin.video.form', [
            'video' => $video,
            'categories' => $this->categoryVideo->select('id', 'name')->orderBy('name', 'DESC')->get(),
            'types' => TypeVideoEnum::ARRAY_TYPE_VIDEOS
        ]);
    }

    public function update(VideoRequest $request, Video $video): RedirectResponse
    {
        $data = $request->all();

        /** @var UploadedFile|null $videoUpload */
        $videoUpload = $data['video_upload'] ?? null;

        /** @var UploadedFile|null $image */
        $image = $data['image'] ?? null;
        try {
            if ($videoUpload !== null) {
                if (!$videoSaved = $videoUpload->store('videos')) {
                    Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');

                    return redirect()
                        ->back()
                        ->withInput();
                }

                $data['video'] = $videoSaved;
            }

            if ($image !== null) {
                if (!$imageSaved = $image->store('images')) {
                    Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');

                    return redirect()
                        ->back()
                        ->withInput();
                }

                $data['image'] = $imageSaved;
            }
            $video->update($data);

            Alert('Sucesso!', 'Atualizado com sucesso!', 'success');
            return redirect()->route('admin.video.index');
        } catch (\Throwable $th) {

            if (env('app_debug')) {
                dd($th->getMessage());
            }

            Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');
            return redirect()
                ->back()
                ->withErro('Ocorreu um erro!')
                ->withInput();
        }
    }

    public function destroy(Video $video): RedirectResponse
    {
        try {
            if ($video->is_upload) {
                Storage::delete($video->video);
            }

            if ($video->image) {
                Storage::delete($video->image);
            }

            $video->delete();

            Alert('Sucesso!', 'Excluído com sucesso!', 'success');
            return redirect()->back();
        } catch (\Throwable $th) {
            Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');
            return redirect()
                ->back()
                ->withErro('Ocorreu um erro!')
                ->withInput();
        }
    }
}

app/Http/Controllers/Site/VideoController.php
<?php

namespace App\Http\Controllers\Site;

use App\Enums\TypeVideoEnum;
use App\Http\Controllers\Controller;
use App\Models\Video;
use Illuminate\Contracts\View\View;
use Illuminate\Http\Request;

class VideoController extends Controller
{
    private Video $video;

    public function __construct(Video $video)
    {
        $this->video = $video;
    }

    public function __invoke(): View
    {
//        dd(
//            $this->video
//                ->with('category')
//                ->where('type_video', TypeVideoEnum::VIDEO_YOUTUBE)
//                ->orderBy('created_at')
//                ->first()->video_id
//        );
        return view('site.videos', [
            'pageName' => 'Vídeos',
            'videos' => $this->video
                ->with('category')
                ->orderBy('created_at', 'DESC')
                ->get()
        ]);
    }
}

resources/views/admin/video/form.blade.php
@extends('adminlte::page')

@section('title', isset($video) ? 'Edição de vídeo' : 'Cadastrar vídeo')

@section('content_header')
    <div class="row">
        <div class="col-sm-6">
            <h1>
                Vídeo
            </h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard.index') }}">
                        Início
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.video.index') }}">
                        Vídeos
                    </a>
                </li>

                <li class="breadcrumb-item active">
                    Adicionar
                </li>
            </ol>
        </div>
    </div>
@endsection

@section('content')
    @include('sweetalert::alert')

    <div class="card card-outline card-success">
        <div class="card-header">
            <div class="card-title">
                {{ isset($video) ? 'Edição vídeo' : 'Cadastrar vídeo' }}
            </div>
        </div>

        <div class="card-body">
            @if (isset($video))
                <form action="{{ route('admin.video.update', $video->id) }}" method="POST" enctype="multipart/form-data">
                @method('PUT')
            @else
                <form action="{{ route('admin.video.store') }}" method="POST" enctype="multipart/form-data">
            @endif
                @csrf

                <div class="form-group">
                    <label for="title">Título <span class="text-danger">*</span></label>
                    <input type="text" name="title" id="title" class="form-control @error('title') is-invalid @enderror" value="{{ $video->title ?? old('title') }}" maxlength="150" required>

                    @error('title')
                        <span class="invalid-feedback" role="alert">
                            {{ $message }}
                        </span>
                    @enderror
                </div>

                @isset($video->image)
                    <img src="{{ asset('storage/' . $video->image) }}" height="100" width="100" class="img-responsive img-thumbnail">
                @endisset

                <div class="form-group">
                    <label for="image">Imagem para Capa</label>
                    <input type="file" name="image" id="image" class="form-control-file @error('image') is-invalid @enderror" >

                    @error('image')
                        <span class="invalid-feedback" role="alert">
                            {{ $message }}
                        </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="category_video_id">
                        Categoria <span class="text-danger">*</span>
                    </label>

                    <select name="category_video_id" id="category_video_id" class="form-control @error('category_video_id') is-invalid @enderror">
                        <option value="">Selecione uma categoria</option>
                        @foreach ($categories as $category)
                            <option value="{{ $category->id }}" @if(isset($video)) @if($video->category_video_id === $category->id) selected @endif @else @if(old('category_video_id') == $category->id) selected @endif @endif>
                                {{ $category->name }}
                            </option>
                        @endforeach
                    </select>

                    @error('category_video_id')
                        <span class="invalid-feedback" role="alert">
                            {{ $message }}
                        </span>
                    @enderror
                </div>

                <div class="form-group">
                    <label for="type_video">
                        Tipo de vídeo <span class="text-danger">*</span>
                    </label>

                    <select name="type_video" id="type_video" class="form-control @error('type_video') is-invalid @enderror">
                        <option value="">Selecione um tipo de vídeo</option>
                        @foreach ($types as $key => $type)
                            <option value="{{ $key }}" @if(isset($video)) @if($video->type_video === $key) selected @endif @else @if(old('type_video') == $key) selected @endif @endif>
                                {{ ucfirst($type) }}
                            </option>
                        @endforeach
                    </select>

                    @error('type_video')
                        <span class="invalid-feedback" role="alert">
                            {{ $message }}
                        </span>
                    @enderror
                </div>

                <div class="form-group" id="form-link" style="display: none">
                    <label for="video">Link do vídeo <span class="text-danger">*</span></label>
                    <input type="text" name="video" id="video" class="form-control @error('video') is-invalid @enderror" value="{{ $video->video ?? old('video') }}">

                    @error('video')
                        <span class="invalid-feedback" role="alert">
                            {{ $message }}
                        </span>
                    @enderror
                </div>

                <div class="form-group" id="form-upload" style="display: none">
                    <label for="video_upload">Vídeo <span class="text-danger">*</span></label>
                    <input type="file" name="video_upload" id="video_upload" class="form-control-file @error('video_upload') is-invalid @enderror" >

                    @error('video_upload')
                        <span class="invalid-feedback" role="alert">
                            {{ $message }}
                        </span>
                    @enderror
                </div>


                    <div class="form-group">
                    <small>(<span class="text-danger">*</span>) Campos obrigatórios</small>
                </div>

                <button type="submit" class="btn btn-success">
                    <i class="fa fa-save"></i>
                    {{ isset($video) ? 'Atualizar' : 'Cadastrar' }}
                </button>

                <a href="{{ route('admin.video.index') }}" class="btn btn-secondary">
                    <i class="fa fa-times"></i>
                    Cancelar
                </a>
            </form>
        </div>
    </div>
@endsection

@section('js')
    <script>
        let typeVideo = document.querySelector('#type_video')

        if (typeVideo.value) {
            changeFormVideo(parseInt(typeVideo.value))
        }

        typeVideo.addEventListener('change', function () {
            let typeVideoValue = parseInt(typeVideo.value)

            changeFormVideo(typeVideoValue);
        })

        function changeFormVideo(typeVideoValue) {
            let formUpload = document.querySelector('#form-upload')
            let formLink = document.querySelector('#form-link')

            const videoYoutube = parseInt('{{ \App\Enums\TypeVideoEnum::VIDEO_YOUTUBE }}');
            const videoVimeo = parseInt('{{ \App\Enums\TypeVideoEnum::VIDEO_VIMEO }}');
            const videoUpload = parseInt('{{ \App\Enums\TypeVideoEnum::VIDEO_UPLOAD }}');

            if (typeVideoValue === videoYoutube) {
                document.querySelector('#video').placeholder = 'Ex: https://youtu.be/Ee0Qh_nIoHw'
                formUpload.style.display = 'none'
                formLink.style.display = 'block'
            }

            if (typeVideoValue === videoVimeo) {
                document.querySelector('#video').placeholder = 'Ex: https://vimeo.com/666109154'
                formUpload.style.display = 'none'
                formLink.style.display = 'block'
            }

            if (typeVideoValue === videoUpload) {
                formLink.style.display = 'none'
                formUpload.style.display = 'block'
            }
        }

    </script>
@endsection

resources/views/admin/video/index.blade.php
@extends('adminlte::page')

@section('title', 'Vídeos')

@section('content_header')
    <div class="row">
        <div class="col-sm-6">
            <h1>
                Vídeos
            </h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard.index') }}">
                        Início
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    Vídeos
                </li>
            </ol>
        </div>
    </div>
@endsection

@section('content')
    @include('sweetalert::alert')

    <div class="card card-outline card-primary">
        <div class="card-header">
            <div class="card-title">
                Lista de Vídeos
            </div>
        </div>

        <div class="row justify-content-end mr-3 mt-3">
            <a href="{{ route('admin.video.create') }}" class="btn btn-success">
                <i class="fa fa-plus"></i>
                Adicionar
            </a>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped text-center">
                    <thead>
                        <tr>
                            <th>Título</th>
                            <th>Capa</th>
                            <th>Categoria</th>
                            <th>Data Postagem</th>
                            <th>Ações</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($videos as $video)
                            <tr>
                                <td>
                                    {{ $video->title }}
                                </td>

                                <td>
                                    <img src="{{ $video->image_link }}" height="50" width="50" class="img-responsive img-thumbnail">
                                </td>

                                <td>
                                    {{ $video->category->name }}
                                </td>

                                <td>
                                    {{ $video->created_at->format('d/m/Y H:i') }}
                                </td>

                                <td>
                                    @can('editar video')
                                        <a href="{{ route('admin.video.edit', $video->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Editar">
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    @endcan

                                    @can('excluir video')
                                        <form action="{{ route('admin.video.destroy', $video->id) }}" class="d-inline" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Tem certeza que deseja excluir?')" data-toggle="tooltip" data-placement="top" title="Excluir">
                                                <i class="fa fa-trash-alt"></i>
                                            </button>
                                        </form>
                                    @endcan
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection