routes/web.php
<?php

use App\Http\Controllers\Admin\ACL\RoleController;
use App\Http\Controllers\Admin\CategoryVideoController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\DepartmentController;
use App\Http\Controllers\Admin\ProfileController;
use App\Http\Controllers\Admin\ResumeController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VideoController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\Site\CompanyController;
use App\Http\Controllers\Site\PartnershipController;
use App\Http\Controllers\Site\ResumeController as SiteResumeController;
use App\Http\Controllers\Site\VideoController as SiteVideoController;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Site
Route::name('site.')->group(function () {
    Route::get('/', [HomeController::class, 'index'])->name('index');

//    Route::get('/carreiras', function() {
//        return view('site.carreiras');
//    });
//
    Route::get('/videos', SiteVideoController::class)->name('video');
    Route::get('empresa', CompanyController::class)->name('company');
    Route::get('motivos', PartnershipController::class)->name('partnership');

    Route::get(
        'produtos/mudas',
        fn (): View => view('site.plant_seedlings', ['pageName' => 'Mudas'])
    )->name('seedlings');

    Route::get(
        'produtos/porta-enxertos',
        fn (): View => view('site.grafts', ['pageName' => 'Porta-enxertos'])
    )->name('grafts');

    Route::get(
        'produtos/borbulhas',
        fn (): View => view('site.bubbles', ['pageName' => 'Borbulhas'])
    )->name('bubbles');

    Route::get(
        'contato',
        fn (): View => view('site.contact', ['pageName' => 'Contato'])
    )->name('contact');

    Route::get('carreiras', [SiteResumeController::class, 'index'])->name('career');
    Route::post('carreiras', [SiteResumeController::class, 'store'])->name('career-send');
});


Route::prefix('admin')->name('admin.')->group(function () {
    Route::group(
        ['middleware' => ['auth']],
        function () {
            // Dashboard
            Route::get('/', DashboardController::class)->name('dashboard.index');

            // Perfil
            Route::prefix('perfil')->name('profile.')->group(function () {
                Route::get('/', [ProfileController::class, 'index'])->name('index');
                Route::put('update', [ProfileController::class, 'update'])->name('update');
            });

            // Usuários
            Route::prefix('usuarios')->name('user.')->group(function () {
                Route::get('/', [UserController::class, 'index'])
                    ->name('index')
                    ->can('visualizar usuários');

                Route::group(['middleware' => ['can:cadastrar usuário']], function () {
                    Route::get('/cadastrar', [UserController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [UserController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar usuário']], function () {
                    Route::get('editar/{id}', [UserController::class, 'edit'])->name('edit');
                    Route::put('editar/{id}', [UserController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{id}', [UserController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir usuário');
            });

            // Cargos
            Route::prefix('cargos')->name('role.')->group(function () {

                Route::get('/', [RoleController::class, 'index'])
                    ->name('index')
                    ->can('visualizar cargos');

                Route::group(['middleware' => ['can:cadastrar cargo']], function () {
                    Route::get('/cadastrar', [RoleController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [RoleController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar cargo']], function () {
                    Route::get('editar/{id}', [RoleController::class, 'edit'])->name('edit');
                    Route::put('editar/{id}', [RoleController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{id}', [RoleController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir cargo');

            });

            // Departamentos
            Route::prefix('departamentos')->name('department.')->group(function () {
                Route::get('/', [DepartmentController::class, 'index'])
                    ->name('index')
                    ->can('visualizar departamentos');

                Route::group(['middleware' => ['can:cadastrar departamento']], function () {
                    Route::get('/cadastrar', [DepartmentController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [DepartmentController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar departamento']], function () {
                    Route::get('editar/{department}', [DepartmentController::class, 'edit'])->name('edit');
                    Route::put('editar/{department}', [DepartmentController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{department}', [DepartmentController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir departamento');
            });

            // Currículos
            Route::prefix('curriculos')->name('resume.')->group(function () {
                Route::get('/', [ResumeController::class, 'index'])
                    ->name('index')
                    ->can('visualizar curriculos');

                Route::get('/download/{resume}', [ResumeController::class, 'downloadResume'])
                    ->name('download')
                    ->can('baixar curriculo');

                Route::delete('excluir/{curriculo}', [DepartmentController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir curriculo');
            });

            // Categorias de vídeos
            Route::prefix('categorias-videos')->name('category_video.')->group(function () {
                Route::get('/', [CategoryVideoController::class, 'index'])
                    ->name('index')
                    ->can('visualizar categorias de video');

                Route::group(['middleware' => ['can:cadastrar categoria de video']], function () {
                    Route::get('/cadastrar', [CategoryVideoController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [CategoryVideoController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar categoria de video']], function () {
                    Route::get('editar/{categoryVideo}', [CategoryVideoController::class, 'edit'])->name('edit');
                    Route::put('editar/{categoryVideo}', [CategoryVideoController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{categoryVideo}', [CategoryVideoController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir categoria de video');
            });

            // Vídeos
            Route::prefix('videos')->name('video.')->group(function () {
                Route::get('/', [VideoController::class, 'index'])
                    ->name('index')
                    ->can('visualizar videos');

                Route::group(['middleware' => ['can:cadastrar video']], function () {
                    Route::get('/cadastrar', [VideoController::class, 'create'])->name('create');
                    Route::post('/cadastrar', [VideoController::class, 'store'])->name('store');
                });

                Route::group(['middleware' => ['can:editar video']], function () {
                    Route::get('editar/{video}', [VideoController::class, 'edit'])->name('edit');
                    Route::put('editar/{video}', [VideoController::class, 'update'])->name('update');
                });

                Route::delete('excluir/{video}', [VideoController::class, 'destroy'])
                    ->name('destroy')
                    ->can('excluir video');
            });

        }
    );
});


Auth::routes();

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Illuminate\Support\Facades\DB;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use Notifiable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * Return role_id
     *
     * @return integer|null
     */
    public function getRole(): ?int
    {
        $role = DB::table('model_has_roles')
            ->select('role_id')
            ->where([
                'model_id' => $this->id,
                'model_type' => 'App\Models\User'
            ])
            ->first();

        return $role->role_id ?? null;
    }

    public function isSuper(): bool
    {
        return in_array($this->email, config('acl.super'));
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Http\Requests\UserRequest;
use App\Models\User;
use Illuminate\Contracts\View\View;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Facades\Log;
use Spatie\Permission\Models\Role;

class UserController extends Controller
{
    protected User $user;
    protected Role $role;

    /**
     * Create a new controller instance
     */
    public function __construct(User $user, Role $role)
    {
        $this->user = $user;
        $this->role = $role;
    }

    public function index(): View
    {
        $users = $this->user->all();

        return view('admin.user.index', compact('users'));
    }

    public function create(): View
    {
        $roles = $this->role
            ->where('id', '<>', 1)
            ->get();

        return view('admin.user.create', [
            'roles' => $roles
        ]);
    }

    public function store(UserRequest $request): RedirectResponse
    {
        $data = $request->all();

        try {
            $user = $this->user->create($data);

            if (isset($data['role'])) {
                $user->assignRole($data['role']);
            }

            Alert('Sucesso!', 'Adicionado com sucesso!', 'success');
            return redirect()->route('admin.user.index');
        } catch (\Throwable $th) {
            Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');
            return redirect()
                ->back()
                ->withErro('Ocorreu um erro!')
                ->withInput();
        }
    }

    public function edit(int $id): View
    {
        $user = $this->user->findOrFail($id);
        $roles = $this->role
            ->where('id', '<>', 1)
            ->get();

        return view('admin.user.edit', [
            'user' => $user,
            'roles' => $roles
        ]);
    }

    public function update(UserRequest $request, int $id): RedirectResponse
    {
        $data = $request->all();

        if ($request->password) {
            $data['password'] = bcrypt($data['password']);
        } else {
            unset($data['password']);
        }

        try {
            $user = $this->user->findOrFail($id);

            $user->update($data);

            if (isset($data['role'])) {
                $user->assignRole($data['role']);
            }

            Alert('Sucesso!', 'Atualizado com sucesso!', 'success');
            return redirect()->route('admin.user.index');
        } catch (\Throwable $th) {
            Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');
            return redirect()
                ->back()
                ->withErro('Ocorreu um erro!')
                ->withInput();
        }
    }

    public function destroy(int $id): RedirectResponse
    {
        try {
            $user = $this->user->findOrFail($id);

            $user->delete();

            Alert('Sucesso!', 'Excluído com sucesso!', 'success');
            return redirect()->back();
        } catch (\Throwable $th) {
            Alert('Erro!', 'Ocorreu um erro. Tente novamente.', 'error');
            return redirect()
                ->back()
                ->withErro('Ocorreu um erro!')
                ->withInput();
        }
    }
}

resources/views/admin/user/create.blade.php
@extends('adminlte::page')

@section('content_header')
    <div class="row">
        <div class="col-sm-6">
            <h1>
                Usuários
            </h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard.index') }}">
                        Início
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.user.index') }}">
                        Usuários
                    </a>
                </li>

                <li class="breadcrumb-item active">
                    Adicionar
                </li>
            </ol>
        </div>
    </div>
@endsection

@section('content')
@include('sweetalert::alert')

    <div class="card card-outline card-success">
        <div class="card-header">
            <div class="card-title">
                Adicionar novo usuário
            </div>
        </div>

        <div class="card-body">
            <form action="{{ route('admin.user.store') }}" method="POST">

                @component('admin.user._partials.form', ['roles' => $roles])
                @endcomponent

                <button type="submit" class="btn btn-success">
                    <i class="fa fa-save"></i>
                    Adicionar
                </button>
                <a href="{{ route('admin.user.index') }}" class="btn btn-secondary">
                    <i class="fa fa-times"></i>
                    Cancelar
                </a>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('adminlte::page')

@section('content_header')
    <div class="row">
        <div class="col-sm-6">
            <h1>
                Usuário
            </h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard.index') }}">
                        Início
                    </a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.user.index') }}">
                        Usuários
                    </a>
                </li>

                <li class="breadcrumb-item active">
                    Editar
                </li>
            </ol>
        </div>
    </div>
@endsection

@section('content')
    @include('sweetalert::alert')

    <div class="card card-outline card-success">
        <div class="card-header">
            <div class="card-title">
                Editar usuário
            </div>
        </div>

        <div class="card-body">
            <form action="{{ route('admin.user.update', $user->id) }}" method="POST">
                @method('PUT')

                @component('admin.user._partials.form', ['user' => $user, 'roles' => $roles])
                @endcomponent

                @can('editar usuário')
                    <button type="submit" class="btn btn-success">
                        <i class="fa fa-save"></i>
                        Atualizar
                    </button>
                @endcan
                <a href="{{ route('admin.user.index') }}" class="btn btn-secondary">
                    <i class="fa fa-times"></i>
                    Cancelar
                </a>
            </form>
        </div>
    </div>
@endsection

resources/views/admin/user/index.blade.php
@extends('adminlte::page')

@section('title', 'Usuários')

@section('content_header')
    <div class="row">
        <div class="col-sm-6">
            <h1>
                Usuários
            </h1>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb float-sm-right">
                <li class="breadcrumb-item">
                    <a href="{{ route('admin.dashboard.index') }}">
                        Início
                    </a>
                </li>
                <li class="breadcrumb-item active">
                    Usuários
                </li>
            </ol>
        </div>
    </div>
@endsection

@section('content')
@include('sweetalert::alert')

    <div class="card card-outline card-primary">
        <div class="card-header">
            <div class="card-title">
                Usuários do sistema
            </div>
        </div>

        <div class="row justify-content-end mr-3 mt-3">
            <a href="{{ route('admin.user.create') }}" class="btn btn-success">
                <i class="fa fa-plus"></i>
                Adicionar
            </a>
        </div>

        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped text-center">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nome</th>
                            <th>Email</th>
                            <th>Cargo</th>
                            <th>Ações</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach ($users as $user)
                            <tr>
                                <td>
                                    {{ $user->id }}
                                </td>
                                <td>
                                    {{ $user->name }}
                                <td>
                                    {{ $user->email }}
                                </td>
                                <td>
                                    {{ $user->getRoleNames()->first() ?? '' }}
                                </td>
                                <td>
                                    @if (!$user->isSuper())
                                        @can('editar usuário')
                                            <a href="{{ route('admin.user.edit', $user->id) }}" class="btn btn-sm btn-primary" data-toggle="tooltip" data-placement="top" title="Editar">
                                                <i class="fa fa-edit"></i>
                                            </a>
                                        @endcan
                                    
                                        @can('excluir usuário')
                                            @if (auth()->id() !== $user->id)
                                                <form action="{{ route('admin.user.destroy', $user->id) }}" class="d-inline" method="POST">
                                                    @csrf
                                                    @method('DELETE')
                                                    <button type="submit" class="btn btn-sm btn-danger" onclick="return confirm('Tem certeza que deseja excluir?')" data-toggle="tooltip" data-placement="top" title="Editar">
                                                        <i class="fa fa-trash-alt"></i>
                                                    </button>
                                                </form>
                                            @endif
                                        @endcan
                                    @endif
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>

@endsection